name: Deployment - Production

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy on production environment
    runs-on: ubuntu-latest
    steps:
    - name: Deploying to ${{ secrets.SSH_HOST }} via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd /var/www/production.lareco.fr
          git stash
          git pull
          cd front-end
          npm i
          npm run build
          cd ../back-end
          npm i --production
          npx prisma migrate deploy
          pm2 restart production.lareco.fr --update-env